name: Python Package

on:
  push:
    tags:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.8, 3.8, 3.8, 3.8, 3.8]
        aio-available: [false, true]
        include:
          - python-version: 3.8
            aio-available: true
          - python-version: 3.8
            aio-available: true
            dist: xenial
          - python-version: 3.8
            aio-available: true
            dist: xenial

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -U pip setuptools wheel
          pip install -U pytest pytest-cov coveralls
          if [ "${{ matrix.aio-available }}" = "true" ]; then pip install -U pytest-asyncio; fi
          pip install -e .

      - name: Run tests
        run: |
          py.test --cov-config .coveragerc --cov=pydispatch

      - name: Upload coverage to Coveralls
        if: success() && matrix.python-version != '3.8'
        run: coveralls --rcfile=".coveragerc"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && matrix.python-version == '3.8'

    steps:
      - name: Deploy to PyPI
        run: |
          pip install twine
          python setup.py sdist bdist_wheel
          twine upload dist/* -u __token__ -p ${{ secrets.PYPI_TOKEN }}

