name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.8, 3.8, 3.8, 3.9]
        django-version: [1.9, 1.10, 1.11.17, 2.0, 2.2, 3.1, 3.2]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.python-version }}" == "3.8" && ("${{ matrix.django-version }}" == "2.0" || "${{ matrix.django-version }}" == "2.2" || "${{ matrix.django-version }}" == "3.1" || "${{ matrix.django-version }}" == "3.2") ]]; then
            echo "Skipping Django ${{ matrix.django-version }} on Python 3.8"
            exit 0
          fi
          if [[ "${{ matrix.python-version }}" == "3.8" && ("${{ matrix.django-version }}" == "1.9" || "${{ matrix.django-version }}" == "1.10") ]]; then
            echo "Skipping Django ${{ matrix.django-version }} on Python 3.8"
            exit 0
          fi
          if [[ "${{ matrix.python-version }}" == "3.9" && ("${{ matrix.django-version }}" == "1.9" || "${{ matrix.django-version }}" == "1.10") ]]; then
            echo "Skipping Django ${{ matrix.django-version }} on Python 3.9"
            exit 0
          fi
          pip install Django==${{ matrix.django-version }}

      - name: Run tests
        run: python test_manage.py test
