name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8, 3.8, 3.8, 3.8, 3.9, 'pypy-3.6']
        toxenv: 
          - pre-commit
          - py38-2.2
          - py38-2.2
          - py38-2.2
          - py38-2.2
          - pypy-3.6-2.2
          - py38-3.0
          - py38-3.0
          - py38-3.0
          - pypy-3.6-3.0
          - py38-3.1
          - py38-3.1
          - py38-3.1
          - pypy-3.6-3.1
          - py38-3.2
          - py38-3.2
          - py38-3.2
          - py39-3.2
          - pypy-3.6-3.2
          - py38-main
          - py39-main
          - pypy-3.6-main

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install coverage tox

      - name: Run tests
        run: |
          tox -e ${{ matrix.toxenv }}

      - name: Upload coverage to Coveralls
        if: success()
        run: coveralls

    # Allow failures for specific jobs
    continue-on-error: ${{ matrix.toxenv == 'py38-main' || matrix.toxenv == 'py39-main' || matrix.toxenv == 'pypy-3.6-main' }}

