name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.8, 3.8, 3.8, 3.8, 3.9]
        geos-version: [3.8.2, 3.8.4, 3.8.3, 3.8.1, 3.8.1]
        numpy-version: [1.10.4, 1.13.3, 1.15.4, 1.17.5, 1.19.4]
        include:
          - python-version: 3.9
            geos-version: main
            numpy-version: latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache GEOS and pip
        uses: actions/cache@v2
        with:
          path: |
            $HOME/geosinstall
            ~/.cache/pip
          key: ${{ runner.os }}-geos-${{ matrix.geos-version }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install GEOS
        run: |
          export GEOS_INSTALL=$HOME/geosinstall/geos-${{ matrix.geos-version }}
          ./ci/install_geos.sh
          pip install --disable-pip-version-check --upgrade pip
          pip install --upgrade wheel
          if [ "${{ matrix.geos-version }}" = "main" ]; then
            pip install --upgrade --pre Cython numpy pytest;
          else
            pip install --upgrade Cython "numpy==${{ matrix.numpy-version }}" pytest;
          fi
          export LD_LIBRARY_PATH=$GEOS_INSTALL/lib
          export PATH=$GEOS_INSTALL/bin:$PATH
          python setup.py build_ext --inplace
          pip install --no-deps -e .

      - name: Run tests
        run: pytest --doctest-modules

      - name: Allow failures for main
        if: matrix.geos-version == 'main'
        run: echo "This job is allowed to fail."

