name: CI

on:
  push:
    tags: true
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.8, 3.8, '3.8', '3.8']
        include:
          - env: BUILD=docs
          - env: BUILD=pep8
          - env: BUILD=cover

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Uninstall conflicting packages
        run: |
          pip uninstall -y nose mock

      - name: Install dependencies
        run: |
          pip install pbr tox tox-travis
          pip install -r doc/requirements.txt .[test]

      - name: Run tests
        run: |
          case ${{ env.BUILD }} in
              docs|pep8|cover)
                  tox -e ${{ env.BUILD }}
                  ;;
              *)
                  tox
                  ;;
          esac

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.0
        with:
          username: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          distributions: sdist bdist_wheel
          skip_existing: true

# Note: You need to set the PYPI_TOKEN secret in your GitHub repository settings.

