name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: yandex/clickhouse-server:19.3.8
        ports:
          - 9000:9000
          - 8123:8123
        options: >-
          --ulimit nofile=262144:262144
          
    strategy:
      matrix:
        python-version: [3.8, 3.8, 3.8, 3.8, 3.8]
        version: [19.3.8, 18.14.9]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install flake8 flake8-print coveralls

      - name: Run flake8
        run: flake8

      - name: Run tests with coverage
        run: coverage run --source=clickhouse_sqlalchemy setup.py test

      - name: Upload coverage to Coveralls
        run: coveralls

      - name: Update /etc/hosts
        run: echo '127.0.0.1 clickhouse-server' | sudo tee -a /etc/hosts

      - name: Override setup.cfg
        run: sed -i 's/^host=localhost$/host=clickhouse-server/' setup.cfg

      - name: Docker login
        if: env.DOCKER_PASSWORD != ''
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Start ClickHouse server
        run: docker run -d -p 127.0.0.1:9000:9000 -p 127.0.0.1:8123:8123 --name test-clickhouse-server --ulimit nofile=262144:262144 yandex/clickhouse-server:${{ matrix.version }}

      - name: List Docker containers
        run: docker ps -a

